# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]

pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Tushant Sharma
tagline:          'Electrical engineer. Electronics enthusiast. Blogger. Tweeter. Footballer.'
url:              http://www.tushantsharma.com
shorturl:         tushantsharma.com

author:
  name:           'Tushant Sharma'
  url:            https://twitter.com/SharmaTushant

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/Jadax/jadax.github.io

# This is the list of pages to incldue in the header of the website.
pages_list:       
  About: '/about/'
  Blog: '/archive/'
  Academic: '/academic/'
  Projects: '/projects/'
  Feed: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
