markdown:         rdiscount
pygments:         true
rdiscount:
  extensions: [smart]

permalink:        pretty

name: Tushant Sharma
url: http://www.tushantsharma.com
description: Electrical and Electronics graduate from Aston University, United Kingdom.
twitter: SharmaTushant
github: Jadax
gravatar_url: http://www.gravatar.com/avatar/930e638d1fddb2f7e193798875dc7489.png

disqus_short_name: Jadax
disqus_show_comment_count: false

googleplus_user: 110638987392974757846
googleplus_hidden: false

pages_list:       
  Blog: '/archive/'
  About: '/about/'
  Academic: '/academic/'
  Projects: '/projects/'
  Feed: '/atom.xml'
  
google_analytics_tracking_id: UA-51514707-1